### ISSUE TITLE
Why isn't the definition of the variable with the initialization in one line?

### ISSUE THREAD

**Issue by TheZitroX** [jondurrant/RPIPicoStepperExp#1]
https://github.com/jondurrant/RPIPicoStepperExp/blob/f04764e7c1d211d7ebae1b0e0c8c5e9e9cfacdc5/FreeRTOS-28byj-48/src/main.cpp#L181-L182C28

**Comment by TheZitroX** [comment]
use a makro on top of the file for easy change

**Comment by jondurrant** [comment]
It's an experiment code set used to explain some concepts. So sometimes I follow coding approaches that mean that a snip of code on a slide will be clearer, even if normal coding standard would have the definition elsewhere.

There is nothing wrong with using stdio approaches in C++. It is part of the languaage.

**Comment by TheZitroX** [comment]
I am not trying to be wrong at you, just saying what i learned the last 3y.
Therfore:

"_The question here that might come up is why use another header file and not use stdio.h"_ this is because in c++ the input and output are treated as streams and the header file is written in such a way that this improves type safety, reduces errors, allows extensibility, provides subclass abilitys and improves the performance.

**Comment by jondurrant** [comment]
I appreciate the feedback and agree with your statement.  Sometimes though I find the more traditional C capabilities clearer, so I continue to use them.

I probably do suffer from learning C before C++. After 30 years of C coding, I think I may need therapy to change;-)

**Comment by TheZitroX** [comment]
Yeah, haha.
Its two different generations, your code will help my not so C friendly physicist for making his thesis at school.

Im in my first footsteps in my career, you probably know more than me🙌.

Kind regards,
John.

**Comment by jondurrant** [comment]
It's not about knowing more or competition. It's about sharing and debate so we all learn together. 

Thank you for looking and the code and engaging. Always happy to chat about tech. Otherwise I would not put this code up here or run YouTube channel.

Jon

**Comment by TheZitroX** [comment]
Maybe for learning purposes you are interested in:

Since the C++ 1998 standard, no C++ header file has had a “.h” extension. You never use “#include <iostream.h>… you use “#include \<iostream\>”.

Old C++ programs that want to use C facilities can continue to use “#include “stdio.h”, but all new ones that want to use it should use “**include \<cstdio\>**” (as Sergey recommended) because it puts things into the std namespace, which is where system functions belong.

C++ supports both its own stream I/O and the older C I/O and it always will… there are just too many dependences on the C I/O’s presence. _There are optimizations for programs that do not ever use C I/O_ (search for “sync_with_stdio” for more details).

https://www.quora.com/Why-dont-we-use-include-stdio-h-in-C
